Temporary Fix

diff --git a/BaseHOT/suricata_opt/nested/prototype.yaml b/BaseHOT/suricata_opt/nested/prototype.yaml
--- a/BaseHOT/suricata_opt/nested/prototype.yaml
+++ b/BaseHOT/suricata_opt/nested/prototype.yaml
@@ -27,40 +27,40 @@ resources:
             get_resource: external_CP
         - port:
             get_resource: elk_CP
-      user_data_format: SOFTWARE_CONFIG
-      str_replace:
-        template: |
-          #!/bin/bash
-          #!/bin/bash
-          echo "Configuring iptables with internal IP $internal_ip and external IP $external_ip"
-          
-          # Install iptables
-          apt-get update
-          apt-get install -y iptables
-          
-          # Enable IP forwarding
-          sysctl -w net.ipv4.ip_forward=1
-          
-          # Identify network interfaces based on IP addresses
-          INTERNAL_IFACE=$(ip addr show | grep "$internal_ip" | awk '{print $NF}')
-          EXTERNAL_IFACE=$(ip addr show | grep "$external_ip" | awk '{print $NF}')
-          
-          # Check if interfaces are found
-          if [ -z "$INTERNAL_IFACE" ] || [ -z "$EXTERNAL_IFACE" ]; then
-          echo "Failed to identify network interfaces."
-          exit 1
-          fi
-          
-          # Apply iptables rules
-          iptables -A FORWARD -i $INTERNAL_IFACE -o $EXTERNAL_IFACE -j ACCEPT
-          iptables -A FORWARD -i $EXTERNAL_IFACE -o $INTERNAL_IFACE -j ACCEPT
-          iptables -t nat -A POSTROUTING -o $EXTERNAL_IFACE -j MASQUERADE
-          iptables -t nat -A POSTROUTING -o $INTERNAL_IFACE -j MASQUERADE
-        
-          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
-        params:
-          $internal_ip: { get_attr: [ internal_CP, fixed_ips, 0, ip_address ] }
-          $external_ip: { get_attr: [ external_CP, fixed_ips, 0, ip_address ] }
+#      user_data_format: SOFTWARE_CONFIG
+#      str_replace:
+#        template: |
+#          #!/bin/bash
+#          #!/bin/bash
+#          echo "Configuring iptables with internal IP $internal_ip and external IP $external_ip"
+#
+#          # Install iptables
+#          apt-get update
+#          apt-get install -y iptables
+#
+#          # Enable IP forwarding
+#          sysctl -w net.ipv4.ip_forward=1
+#
+#          # Identify network interfaces based on IP addresses
+#          INTERNAL_IFACE=$(ip addr show | grep "$internal_ip" | awk '{print $NF}')
+#          EXTERNAL_IFACE=$(ip addr show | grep "$external_ip" | awk '{print $NF}')
+#
+#          # Check if interfaces are found
+#          if [ -z "$INTERNAL_IFACE" ] || [ -z "$EXTERNAL_IFACE" ]; then
+#          echo "Failed to identify network interfaces."
+#          exit 1
+#          fi
+#
+#          # Apply iptables rules
+#          iptables -A FORWARD -i $INTERNAL_IFACE -o $EXTERNAL_IFACE -j ACCEPT
+#          iptables -A FORWARD -i $EXTERNAL_IFACE -o $INTERNAL_IFACE -j ACCEPT
+#          iptables -t nat -A POSTROUTING -o $EXTERNAL_IFACE -j MASQUERADE
+#          iptables -t nat -A POSTROUTING -o $INTERNAL_IFACE -j MASQUERADE
+#
+#          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
+#        params:
+#          $internal_ip: { get_attr: [ internal_CP, fixed_ips, 0, ip_address ] }
+#          $external_ip: { get_attr: [ external_CP, fixed_ips, 0, ip_address ] }
 
   internal_CP:
     type: OS::Neutron::Port
