Updated script

diff --git a/BaseHOT/suricata_opt/nested/prototype.yaml b/BaseHOT/suricata_opt/nested/prototype.yaml
--- a/BaseHOT/suricata_opt/nested/prototype.yaml
+++ b/BaseHOT/suricata_opt/nested/prototype.yaml
@@ -53,27 +53,41 @@ resources:
     type: OS::Heat::SoftwareConfig
     properties:
       group: script
+      inputs:
+        - name: internal_ip
+        - name: external_ip
       config: |
         #!/bin/bash
+        echo "Configuring iptables with internal IP $internal_ip and external IP $external_ip"
+        
+        # Install iptables
         apt-get update
         apt-get install -y iptables
-
+        
+        # Enable IP forwarding
         sysctl -w net.ipv4.ip_forward=1
+        
+        # Identify network interfaces based on IP addresses
+        INTERNAL_IFACE=$(ip addr show | grep "$internal_ip" | awk '{print $NF}')
+        EXTERNAL_IFACE=$(ip addr show | grep "$external_ip" | awk '{print $NF}')
+        
+        # Check if interfaces are found
+        if [ -z "$INTERNAL_IFACE" ] || [ -z "$EXTERNAL_IFACE" ]; then
+          echo "Failed to identify network interfaces."
+          exit 1
+        fi
+        
+        # Apply iptables rules
+        iptables -A FORWARD -i $INTERNAL_IFACE -o $EXTERNAL_IFACE -j ACCEPT
+        iptables -A FORWARD -i $EXTERNAL_IFACE -o $INTERNAL_IFACE -j ACCEPT
+        iptables -t nat -A POSTROUTING -o $EXTERNAL_IFACE -j MASQUERADE
 
-        iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT
-        iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
-        iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
-        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
-
-        echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
-      inputs:
-        - name: eth0
-          value: { get_attr: [Prototype, networks, 0, fixed_ips, 0, ip_address] }
-        - name: eth1
-          value: { get_attr: [Prototype, networks, 1, fixed_ips, 0, ip_address] }
 
   ip_tables_deployment:
     type: OS::Heat::SoftwareDeployment
     properties:
       config: { get_resource: set_ip_table_config }
       server: { get_resource: Prototype }
+      input_values:
+        internal_ip: { get_attr: [ internal_CP, fixed_ips, 0, ip_address ] }
+        external_ip: { get_attr: [ external_CP, fixed_ips, 0, ip_address ] }
