Update

diff --git a/custom_elements/zeek/install.d/90-install-zeek b/custom_elements/zeek/install.d/90-install-zeek
--- a/custom_elements/zeek/install.d/90-install-zeek
+++ b/custom_elements/zeek/install.d/90-install-zeek
@@ -1,8 +1,17 @@
 #!/bin/bash
 
-set -eux
+set -e
 
+# Add Zeek's repository and key for Ubuntu 22.04
 echo 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /' | tee /etc/apt/sources.list.d/security:zeek.list
-curl -fsSL https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
+curl -fsSL https://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/security_zeek.gpg > /dev/null
+
+# Update and install Zeek 6.0
 apt update
-apt install zeek-6.0
+apt install -y zeek-6.0
+
+# Enable Zeek to start on boot
+systemctl enable zeek
+
+# Cleanup
+apt-get clean
